version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    container_name: increate-frontend
    ports:
      - "8081:80"
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: increate-backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3000"
    restart: always
    depends_on:
      - ffmpeg
      - whisper
    volumes: 
      - ./media:/media
    networks:
      - app-network

  ffmpeg:
    build:
      context: ./ffmpeg
      dockerfile: Dockerfile.ffmpeg
    container_name: ffmpeg
    restart: always
    volumes:
      - ./media:/media  # Shared volume for file access
    networks:
      - app-network

  whisper:
    build:
      context: ./whisper
      dockerfile: Dockerfile.whisper
    container_name: whisper-openai
    restart: always
    volumes:
      - ./media:/media  # Shared volume for file access
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
